apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # IAM role to use for the node identity.Must specify one of "role" or "instanceProfile" for Karpenter to launch nodes
  role: "KarpenterNodeRole-${CLUSTER-NAME}"
  #instanceProfile: "KarpenterNodeInstanceProfile-${CLUSTER_NAME}"
  subnetSelectorTerms:
  # Select on any subnet that has the "karpenter.sh/discovery: ${CLUSTER_NAME}"
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  # Required, discovers security groups to attach to instances 
  securityGroupSelectorTerms:
  # Either you can use tag labor selector, or sg name or sg id.
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
        environment: test
    - name: ${sg-name}
    - id: ${sg-id}
  # Required, resolves a default ami i.e AL2, Populate it Custom to use your own eks customised AMI.
  amiFamily: Custom
  amiSelectorTerms:
    - id: "${ami-id}"
  tags:
  # Following tags will be attached to the VMs provisioned by Karpenter.
    Env: Test
    Name: Test.${cluster-Name}
  userData:
    |
    ${Custom-User specific data}